name: Firmware release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Extract build version
        id: get_version
        uses: battila7/get-version-action@v3

      - name: Run PlatformIO - pilot
        env:
          VERSION: ${{ steps.get_version.outputs.version-without-v }}
          BOARD_NUMBER: 1
        run: pio run

      - name: Run PlatformIO - co-pilot
        env:
          VERSION: ${{ steps.get_version.outputs.version-without-v }}
          BOARD_NUMBER: 2
        run: pio run

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/**/firmware*.uf2

      - name: Archive MobiFlight configuration files
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: MobiFlight Resources/*.*

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            .pio/build/**/firmware*.uf2
            MobiFlight Resources/*.*
